<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>elfin_robot_driver</name>
    <version>0.0.1</version>
    <description>Elfin ROS2 driver for Elfin robots</description>
    <maintainer email="medvedevigorek@gmail.com">Igor Medvedev</maintainer>
    <license>TODO: License declaration</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>rclcpp</depend>
    <depend>pluginlib</depend>
    <depend>hardware_interface</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
